version: "3.8"

services:
  database:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: SqlServerDB
    ports:
      - 1433:1433
    env_file:
      - "./.env"
    volumes:
      - ./temp/mssqldata:/var/opt/mssql

volumes:
  mssqldata:
