version: "3.8"

services:
  database:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: SqlServerDB
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    volumes:
      - ./temp/mssqldata:/var/opt/mssql

volumes:
  mssqldata:
