@basepath=http://localhost:8000
@testEmail="vinod@email.com"

GET {{basepath}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Vinod",
    "lastName": "Rastogi",
    "email": {{testEmail}},
    "password": "password",
    "address": {
        "street": "9th Street",
        "city": "Hauz Khaz",
        "state": "New Delhi",
        "countryCode": "IN",
        "zipcode": "102101"
    }
}

### Login

POST {{basepath}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": {{testEmail}},
    "password": "password1"
}
